const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  openDirectory: () => ipcRenderer.invoke('open-directory'),
  heartbeat: () => ipcRenderer.invoke('heartbeat'),
  openFile: () => ipcRenderer.invoke('open-file'),
  showSaveDialog: (options) => ipcRenderer.invoke('show-save-dialog', options),
  showOpenDialog: (options) => ipcRenderer.invoke('show-open-dialog', options),
  scanDirectory: (path) => ipcRenderer.invoke('scan-directory', path),
  listDirectory: (path, showIgnored) => ipcRenderer.invoke('list-directory', path, showIgnored),
  searchFiles: (repoPath, query) => ipcRenderer.invoke('search-files', repoPath, query),
  searchAdvanced: (repos, options) => ipcRenderer.invoke('search-advanced', repos, options),
  readFile: (path) => ipcRenderer.invoke('read-file', path),
  createDirectory: (path) => ipcRenderer.invoke('create-directory', path),
  readFileBase64: (path) => ipcRenderer.invoke('read-file-base64', path),
  writeFile: (path, content) => ipcRenderer.invoke('write-file', path, content),
  moveFile: (src, dest) => ipcRenderer.invoke('move-file', src, dest),
  moveFileForce: (src, dest) => ipcRenderer.invoke('move-file-force', src, dest),
  copyFile: (src, dest) => ipcRenderer.invoke('copy-file', src, dest),
  copyFileForce: (src, dest) => ipcRenderer.invoke('copy-file-force', src, dest),
  renameItem: (oldPath, newPath) => ipcRenderer.invoke('rename-item', oldPath, newPath),
  gitStatus: (path) => ipcRenderer.invoke('git-status', path),
  gitQuickStatus: (path) => ipcRenderer.invoke('git-quick-status', path),
  gitRawStatus: (path) => ipcRenderer.invoke('git-raw-status', path),
  gitStashSave: (path, message) => ipcRenderer.invoke('git-stash-save', path, message),
  gitStashList: (path) => ipcRenderer.invoke('git-stash-list', path),
  gitStashPop: (path, index) => ipcRenderer.invoke('git-stash-pop', path, index),
  gitStashApply: (path, index) => ipcRenderer.invoke('git-stash-apply', path, index),
  gitStashDrop: (path, index) => ipcRenderer.invoke('git-stash-drop', path, index),
  gitPull: (path, force) => ipcRenderer.invoke('git-pull', path, force),
  gitFetch: (path) => ipcRenderer.invoke('git-fetch', path),
  gitMerge: (path) => ipcRenderer.invoke('git-merge', path),
  gitPush: (path, force) => ipcRenderer.invoke('git-push', path, force),
  gitPublishSequence: (path, cloneUrl) => ipcRenderer.invoke('git-publish-sequence', path, cloneUrl),
  gitGetCommits: (path) => ipcRenderer.invoke('git-get-commits', path),
  gitRevertToCommit: (path, hash) => ipcRenderer.invoke('git-revert-to-commit', path, hash),
  gitRestoreToHead: (path) => ipcRenderer.invoke('git-restore-to-head', path),
  gitNukeReinit: (path) => ipcRenderer.invoke('git-nuke-reinit', path),
  gitRestoreFile: (path, filePath) => ipcRenderer.invoke('git-restore-file', path, filePath),
  gitCreateBranch: (path, name) => ipcRenderer.invoke('git-create-branch', path, name),
  gitDeleteBranch: (path, name) => ipcRenderer.invoke('git-delete-branch', path, name),
  gitRenameBranch: (path, oldName, newName) => ipcRenderer.invoke('git-rename-branch', path, oldName, newName),
  gitStageAll: (path) => ipcRenderer.invoke('git-stage-all', path),
  gitStageFile: (path, filePath) => ipcRenderer.invoke('git-stage-file', path, filePath),
  gitUnstageAll: (path) => ipcRenderer.invoke('git-unstage-all', path),
  gitUnstageFile: (path, filePath) => ipcRenderer.invoke('git-unstage-file', path, filePath),
  gitStopTracking: (path, filePath) => ipcRenderer.invoke('git-stop-tracking', path, filePath),
  gitStartTracking: (path, filePath) => ipcRenderer.invoke('git-start-tracking', path, filePath),
  gitIsTracked: (path, filePath) => ipcRenderer.invoke('git-is-tracked', path, filePath),
  gitCommit: (path, message, amend) => ipcRenderer.invoke('git-commit', path, message, amend),
  getBranches: (path) => ipcRenderer.invoke('git-get-branches', path),
  getRemotes: (path) => ipcRenderer.invoke('git-get-remotes', path),
  addRemote: (path, name, url) => ipcRenderer.invoke('git-add-remote', path, name, url),
  removeRemote: (path, name) => ipcRenderer.invoke('git-remove-remote', path, name),
  setRemoteUrl: (path, name, url) => ipcRenderer.invoke('git-set-remote-url', path, name, url),
  switchBranch: (path, branchName) => ipcRenderer.invoke('git-switch-branch', path, branchName),
  getFullDiff: (path) => ipcRenderer.invoke('git-get-full-diff', path),
  getStagedDiff: (path) => ipcRenderer.invoke('git-get-staged-diff', path),
  getCommitDiff: (path, hash) => ipcRenderer.invoke('git-get-commit-diff', path, hash),
  generateCommitMsg: (diff) => ipcRenderer.invoke('generate-commit-msg', diff),
  getChangedFiles: (path) => ipcRenderer.invoke('git-changed-files', path),
  getDetailedChanges: (path) => ipcRenderer.invoke('git-detailed-changes', path),
  getFileDiff: (repoPath, filePath) => ipcRenderer.invoke('git-file-diff', repoPath, filePath),
  getFilePatch: (repoPath, filePath) => ipcRenderer.invoke('git-get-patch', repoPath, filePath),
  applyPatch: (repoPath, patchString) => ipcRenderer.invoke('git-apply-patch', repoPath, patchString),
  gitSubtreePush: (path, prefix, remoteUrl, branch, force) => ipcRenderer.invoke('git-subtree-push', path, prefix, remoteUrl, branch, force),
  gitSubtreePull: (path, prefix, remoteUrl, branch) => ipcRenderer.invoke('git-subtree-pull', path, prefix, remoteUrl, branch),
  gitInit: (path) => ipcRenderer.invoke('git-init', path),
  gitClone: (url, dest) => ipcRenderer.invoke('git-clone', url, dest),
  getRepositories: () => ipcRenderer.invoke('get-repositories'),
  saveRepositories: (repos) => ipcRenderer.invoke('save-repositories', repos),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  getThemes: () => ipcRenderer.invoke('get-themes'),
  saveTheme: (name, ini) => ipcRenderer.invoke('save-theme', { name, ini }),
  deleteTheme: (name) => ipcRenderer.invoke('delete-theme', name),
  exportSettings: () => ipcRenderer.invoke('export-settings'),
  importSettings: () => ipcRenderer.invoke('import-settings'),
  getAvailableShells: () => ipcRenderer.invoke('get-available-shells'),
  fetchGitHubRepos: (token) => ipcRenderer.invoke('github-fetch-repos', token),
  createGitHubRepo: (token, name, isPrivate) => ipcRenderer.invoke('github-create-repo', token, name, isPrivate),
  deleteGitHubRepo: (token, owner, repo) => ipcRenderer.invoke('github-delete-repo', token, owner, repo),
  getGitHubRepo: (token, owner, repo) => ipcRenderer.invoke('github-get-repo', token, owner, repo),
  updateGitHubRepoVisibility: (token, owner, repo, isPrivate) => ipcRenderer.invoke('github-update-repo-visibility', token, owner, repo, isPrivate),
  fetchGitignoreTemplates: () => ipcRenderer.invoke('github-fetch-gitignore-templates'),
  fetchGitignoreContent: (name) => ipcRenderer.invoke('github-fetch-gitignore-content', name),
  fetchLicenseTemplates: () => ipcRenderer.invoke('github-fetch-license-templates'),
  fetchLicenseContent: (key) => ipcRenderer.invoke('github-fetch-license-content', key),
  getWorkspaceStats: (rootPath) => ipcRenderer.invoke('get-workspace-stats', rootPath),
  getGitConfig: () => ipcRenderer.invoke('get-git-config'),
  saveGitConfig: (content) => ipcRenderer.invoke('save-git-config', content),
  ensureGithubSSHTrust: () => ipcRenderer.invoke('ensure-github-ssh-trust'),
  syncTokenToGit: (token) => ipcRenderer.invoke('git-sync-token', token),
  clearGitCreds: () => ipcRenderer.invoke('git-clear-creds'),
  pathExists: (path) => ipcRenderer.invoke('path-exists', path),
  resetApp: () => ipcRenderer.invoke('reset-app'),
  sendNotification: (options) => ipcRenderer.invoke('send-notification', options),
  reportError: (title, message) => ipcRenderer.invoke('report-error', { title, message }),
  isWindows: process.platform === 'win32',

  // Terminal IPCs
  terminalInput: (data) => ipcRenderer.send('terminal-input', data),
  onTerminalData: (callback) => ipcRenderer.on('terminal-data', (_event, value) => callback(value)),
  onTerminalCommand: (callback) => ipcRenderer.on('terminal-command', (_event, value) => callback(value)),
  onConsoleCommand: (callback) => ipcRenderer.on('console-command', (_event, value) => callback(value)),
  terminalResize: (cols, rows) => ipcRenderer.send('terminal-resize', { cols, rows }),

  openVSCode: (path) => ipcRenderer.invoke('open-in-vscode', path),
  openAndroidStudio: (path) => ipcRenderer.invoke('open-in-android-studio', path),
  openExternalTerminal: (path) => ipcRenderer.invoke('open-external-terminal', path),
  openPath: (path) => ipcRenderer.invoke('open-path', path),
  openPathAdmin: (path) => ipcRenderer.invoke('open-path-admin', path),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  revealInExplorer: (path) => ipcRenderer.invoke('reveal-in-explorer', path),
  trashItem: (path) => ipcRenderer.invoke('trash-item', path),
  showContextMenu: (options) => ipcRenderer.invoke('show-context-menu', options),
  onContextMenuCommand: (callback) => ipcRenderer.on('context-menu-command', (_event, value) => callback(value)),
  onExternalChange: (callback) => ipcRenderer.on('external-change', (_event, value) => callback(value)),
  onTriggerAddRepo: (callback) => ipcRenderer.on('trigger-add-repo', (_event, value) => callback(value)),
  onShowError: (callback) => ipcRenderer.on('show-error', (_event, value) => callback(value))
});
